[build]
builder = "nixpacks"     # Usa nixpacks para construir la aplicación Node.js

[deploy]
startCommand = "yarn start"             # Ejecuta el comando definido en package.json del backend
healthcheckPath = "/api/health"         # Verifica que la API esté funcionando
restartPolicyType = "on_failure"        # Reinicia el servicio si falla

[service]
port = 8080                            # Puerto que Railway asigna en producción